In [1]:
import pandas as pd

In [4]:
tabla = "tabla.html"
df = pd.read_html(tabla)[0]
df

,Álbum,Canción 1,Canción 2,Canción 3
0,From Mars to Sirius,Flying Whales,Backbone,Ocean Planet
1,The Way of All Flesh,Vacuity,Adoration for None,Heaviest Matter of the Universe
2,Magma,Stranded,Silvera,Only Pain

In [7]:
tablas = pd.read_html("tabla.html")
primera_banda =tablas [0]
print(primera_banda)
segunda_banda =tablas [1] 
print(segunda_banda)

                  Álbum      Canción 1           Canción 2  \
0   From Mars to Sirius  Flying Whales            Backbone
1  The Way of All Flesh        Vacuity  Adoration for None
2                 Magma       Stranded             Silvera

                         Canción 3
0                     Ocean Planet
1  Heaviest Matter of the Universe
2                        Only Pain
                Álbum             Canción 1                Canción 2  \
0   Master of Puppets               Battery        Master of Puppets
1     The Black Album         Enter Sandman             Sad But True
2  Ride the Lightning  Fight Fire with Fire  For Whom the Bell Tolls

                   Canción 3
0  Welcome Home (Sanitarium)
1             The Unforgiven
2             Creeping Death

In [23]:
mis_tablas = pd.read_html("datos.html")
print("Tablas Detectadas: ", len(mis_tablas))

for i, tabla in enumerate(mis_tablas, start=1):
    print(i)
    display(tabla)

Tablas Detectadas:  3
1

  Escenario         Artista   Hora       Genero
0     Solar       Luna Byte  18:30  Electro Pop
1      Neón  Los Dataframes  19:15        Indie
2    Aurora     SQL Sisters  20:00        Synth
3     Solar     Pandas Crew  21:00         Funk
4      Neón    Null Hunters  22:10         Rock
5   Jupiter     Los Pitones  23:00    Hard Core

2

            Producto   Categoria  Precio_Eur  Unidades
0      Camiseta Glow        Ropa          20        45
1     Tote Bag Pixel  Accesorios          12        60
2       Sticker Pack  Accesorios           5       120
3        Gorra Night        Ropa          15        38
4  Vaso Reutilizable       Hogar           8        72

3

                 Producto Precio  Kalorias    Categoria
0  Hamburguesa de ternera   9,8€      2000        Carne
1     Hamburguesa de tofu   8,6€      1300  Vegetariano
2        Hot Dog de pollo     4€       780        Carne
3           Durum Falafel   5,2€      1100  Vegetariano
4          Kebab de cerdo   7,4€      1500    Carne/td>